blog/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from .views import (
    HomePageView, 
    CreatePostView, 
    UpdatePostView, 
    DeletePostView, 
    PostDetailsView, 
)


urlpatterns = [
    path('posts/<int:pk>/', PostDetailsView.as_view(), name='post_details'), 
    path('posts/<int:pk>/delete/', DeletePostView.as_view(), name='delete_post'), 
    path('posts/<int:pk>/edit/', UpdatePostView.as_view(), name='edit_post'), 
    path('new/', CreatePostView.as_view(), name='new_post'), 
    path('', HomePageView.as_view(), name='home'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
	path('admin/', admin.site.urls), 
	path('', include('blog.urls')), # Blog App
	path('', include('accounts.urls')),  # Auth App
	path('auth/', include('django.contrib.auth.urls')), 
]


handler404 = 'blog.views.error_404'
# handler500 = 'blog.views.error_500'
handler403 = 'blog.views.error_403'
# handler400 = 'blog.views.error_400'

blog/models.py
from django.db import models
from django.urls import reverse



class Post(models.Model):
	author = models.ForeignKey('accounts.CustomUser', on_delete=models.CASCADE)
	photo = models.ImageField(upload_to='images/', null=False, blank=False)
	body = models.TextField()
	date_posted = models.DateTimeField(auto_now_add=True)
	likes = models.ManyToManyField('accounts.CustomUser', blank=True, related_name='likes')
	saved = models.ManyToManyField('accounts.CustomUser', blank=True, related_name='saved')
	comments = models.ManyToManyField('blog.Comment', blank=True, related_name='comments')

	def __str__(self):
		if len(self.body) > 50:
			return self.body[:50] + '...'
		
		else:
			return self.body

	def get_absolute_url(self):
		return reverse('post_details', args=[str(self.pk)])


class Comment(models.Model):
	author = models.ForeignKey('accounts.CustomUser', on_delete=models.CASCADE)
	body = models.TextField()
	date_posted = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		if len(self.body) > 50:
			return self.body[:50] + '...'
		
		else:
			return self.body

blog/views.py
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib import messages
from .models import Post



class PostDetailsView(DetailView):
	model = Post
	template_name = 'blog/post_details.html'

	def get_object(self):
		return Post.objects.get(pk=self.kwargs.get('pk'))


	def post(self, request, pk):
		post = Post.objects.get(pk=pk)
		
		if request.POST['action'] == 'comment':
			if request.POST['comment'] != '':
				if request.user.is_authenticated:
					post.comments.create(
						author=request.user,
						body=request.POST['comment']
					)
					messages.success(request, 'Comment added successfully')
				else:
					messages.error(request, 'You must be logged in to comment')
			else:
				messages.error(request, 'Comment cannot be empty')

			return redirect('post_details', pk=pk)

		elif request.POST['action'] == 'like':
			if request.user.is_authenticated:
				if request.user in post.likes.all():
					post.likes.remove(request.user)
					messages.success(request, 'Like removed successfully')
				else:
					post.likes.add(request.user)
					messages.success(request, 'Like added successfully')
			else:
				messages.error(request, 'You must be logged in to like')

			return redirect('post_details', pk=pk)

		elif request.POST['action'] == 'save':
			if request.user in post.saved.all():
				post.saved.remove(request.user)
				messages.success(request, 'Post removed from saved posts')
			else:
				if request.user.is_authenticated:
					post.saved.add(request.user)
					messages.success(request, 'Post saved')
				else:
					messages.error(request, 'You must be logged in to save posts')
			
			return redirect('post_details', pk=pk)


class DeletePostView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
	model = Post
	template_name = 'blog/delete_post.html'
	success_url = reverse_lazy('home')
	login_url = '/auth/signup/'

	def test_func(self):
		obj = self.get_object()
		return obj.author == self.request.user


class UpdatePostView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
	model = Post
	template_name = 'blog/update_post.html'
	fields = ('photo', 'body')
	login_url = '/auth/signup/'

	def test_func(self):
		obj = self.get_object()
		return obj.author == self.request.user


class CreatePostView(LoginRequiredMixin, CreateView):
	model = Post
	template_name = 'blog/create_post.html'
	fields = ('photo', 'body')
	login_url = '/auth/signup/'

	def form_valid(self, form):
		form.instance.author = self.request.user
		return super().form_valid(form)


class HomePageView(ListView):
	model = Post
	template_name = 'home.html'

	def post(self, request):
		if request.POST['action'].startswith('comment'):
			pk = request.POST['action'].replace('comment_', '')
			post = Post.objects.get(pk=pk)
			if request.POST['comment'] != '':
				if request.user.is_authenticated:
					post.comments.create(
						author=request.user,
						body=request.POST['comment']
					)
					messages.success(request, 'Comment added successfully')
				else:
					messages.error(request, 'You must be logged in to comment')
			else:
				messages.error(request, 'Comment cannot be empty')

			return redirect('post_details', pk=pk)

		elif request.POST['action'].startswith('like'):
			pk = request.POST['action'].replace('like_', '')
			post = Post.objects.get(pk=pk)

			if request.user.is_authenticated:
				if request.user in post.likes.all():
					post.likes.remove(request.user)
					messages.success(request, 'Like removed successfully')
				else:
					post.likes.add(request.user)
					messages.success(request, 'Like added successfully')
			else:
				messages.error(request, 'You must be logged in to like')

			return redirect('home')

		elif request.POST['action'].startswith('save'):
			pk = request.POST['action'].replace('save_', '')
			post = Post.objects.get(pk=pk)

			if request.user in post.saved.all():
				post.saved.remove(request.user)
				messages.success(request, 'Post removed from saved posts')
			else:
				if request.user.is_authenticated:
					post.saved.add(request.user)
					messages.success(request, 'Post saved')				
				else:
					messages.error(request, 'You must be logged in to save posts')
			
			return redirect('home')


def error_404(request, exception):
	return render(request,'error/404.html')

		
def error_403(request, exception):
	return render(request,'error/403.html')

templates/blog/create_post.html
{% extends 'base.html' %}

{% block title %} New Post {% endblock %}

{% block home_color %} white {% endblock %}
{% block add_color %} #a991f7 {% endblock %}

{% block content %}

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="flex justify-center">
        <div class="flex flex-col w-full max-w-md p-12 space-y-4 p-6 rounded-md sm:p-10 dark:bg-gray-900 dark:text-gray-100">
            <h1 style="font-size: 30px; text-align: center;">Create Post</h1>
            {% if form.errors %}
                <p class="text-sm" style="color: red;">Please correct the errors below.</p>
            {% endif %}
            
            <fieldset class="w-full space-y-1 dark:text-gray-100">
                <label for="id_photo" class="block text-sm font-medium">Photo</label>
                <div class="flex">
                    <input type="file" required  name="photo" id="id_photo" accept="image/*" class="px-0.1 py-3 border-2 border-dashed rounded-md dark:border-gray-700 dark:text-gray-400 dark:bg-gray-800">
                </div>
            </fieldset>
            <span class="text-sm" style="color: yellow;">{{ form.errors.photo }}</span>
            
        <label for="body" class="block text-sm font-medium">Your message</label>
        <textarea id="id_body" name="body" rows="7" class="block p-2.5 w-full text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-700 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="Your message..."></textarea>
        <span class="text-sm" style="color: yellow;">{{ form.errors.body }}</span>
        <button class="btn btn-primary">Post</button>
        
        </div>
    </div>
</form>
<br/><br/><br/>

{% endblock %}

templates/blog/delete_post.html
{% extends 'base.html' %}

{% block title %} Delete Post {% endblock %}


{% block content %}

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="flex justify-center">
        <div class="flex flex-col w-full max-w-md p-12 space-y-4 p-6 rounded-md sm:p-10 dark:bg-gray-900 dark:text-gray-100">
            <h1 style="font-size: 25px; text-align: center;">Delete Post</h1>
            <p class="text-md" style="color: yellow;">Are you sure want to delete post?</p>
            
            <fieldset class="w-full space-y-1 dark:text-gray-100">
                <label for="body" class="block text-sm font-medium">Photo: <a href="{{ post.photo.url }}" class="link link-hover link-primary">{{ post.photo }}</a></label>
                <div class="flex">
                    <input disabled type="file"  name="photo" id="id_photo" accept="image/*" class="px-0.1 py-3 border-2 border-dashed rounded-md dark:border-gray-700 dark:text-gray-400 dark:bg-gray-800">
                </div>
            </fieldset>
            <span class="text-sm" style="color: yellow;">{{ form.errors.photo }}</span>
            
        <label for="body" class="block text-sm font-medium">Message</label>
        <textarea disabled id="id_body" name="body" rows="7" class="block p-2.5 w-full text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-700 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="Your message...">{{ post.body }}</textarea>
        <span class="text-sm" style="color: yellow;">{{ form.errors.body }}</span>
        <button class="btn btn-secondary">Delete</button>
        
        </div>
    </div>
</form>
<br/><br/><br/>

{% endblock %}

templates/blog/post_details.html
{% extends 'base.html' %}

{% block title %} Post by {{ post.author.username }} {% endblock %}


{% block content %}
<form method="POST">
  {% csrf_token %}
<div class="flex justify-center">
    <div class="rounded-md shadow-md max-w-lg p-4 shadow-md dark:bg-gray-900 dark:text-gray-100">
      {% for message in messages %}
        {% if message.tags == 'error' %}
          <div class="alert alert-error shadow-lg">
            <div>
              <svg xmlns="http://www.w3.org/2000/svg" class="stroke-current flex-shrink-0 h-6 w-6" fill="none" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 14l2-2m0 0l2-2m-2 2l-2-2m2 2l2 2m7-2a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>
              <span>Error! {{ message }}</span>
            </div>
          </div>
          <br/>  
        {% endif %}
      {% endfor %}
      <div class="flex items-center justify-between p-3">
        <div class="flex items-center space-x-2">
          {% if post.author.profile_pic %}
            <img src="{{ post.author.profile_pic.url }}" alt="" class="object-cover object-center w-8 h-8 rounded-full shadow-sm dark:bg-gray-500 dark:border-gray-700">  
          {% else %}
            <img src="/media/images/default_picture.jpeg" alt="" class="object-cover object-center w-8 h-8 rounded-full shadow-sm dark:bg-gray-500 dark:border-gray-700">
          {% endif %}
            <div class="-space-y-1">
            <h2 class="text-sm font-semibold leading-none"><a href="{% url 'profile' post.author.username %}">{{ post.author.username }}</a></h2>
            <span class="inline-block text-xs leading-none dark:text-gray-400">Posted - {{ post.date_posted }}</span>
          </div>
        </div>
        <div class="dropdown dropdown-end">
          <button title="Open options" type="button">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" class="w-5 h-5 fill-current">
              <path d="M256,144a64,64,0,1,0-64-64A64.072,64.072,0,0,0,256,144Zm0-96a32,32,0,1,1-32,32A32.036,32.036,0,0,1,256,48Z"></path>
              <path d="M256,368a64,64,0,1,0,64,64A64.072,64.072,0,0,0,256,368Zm0,96a32,32,0,1,1,32-32A32.036,32.036,0,0,1,256,464Z"></path>
              <path d="M256,192a64,64,0,1,0,64,64A64.072,64.072,0,0,0,256,192Zm0,96a32,32,0,1,1,32-32A32.036,32.036,0,0,1,256,288Z"></path>
            </svg>
          </button>
          <ul tabindex="0" class="menu menu-compact dropdown-content mt-3 p-2 shadow bg-base-100 rounded-box w-52">
            <li>
              <a class="justify-between" href="{% url 'post_details' post.pk %}">
                Go to post
              </a>
            </li>
            <li><a onclick="copyUrl()">Copy link</a></li>
            {% if user.is_authenticated and request.user == post.author %}
              <li><a href="{% url 'edit_post' post.pk %}">Edit post</a></li>
              <li><a href="{% url 'delete_post' post.pk %}">Delete post</a></li>
            {% endif %}
          </ul>
        </div>
      </div>
      <img src="{{ post.photo.url }}" alt="" class="object-cover object-center w-full h-100 dark:bg-gray-500">
      <div class="p-3 space-y-3">
        <div class="flex items-center justify-between">
          <div class="flex items-center space-x-3">
            <button type="submit" name="action" value="like" title="Like post" class="flex items-center justify-center">
              {% if user in post.likes.all %}
                <span style="color: red;"><i class="fa-solid fa-heart"></i></span>

              {% else %}
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" class="w-5 h-5 fill-current">
                  <path d="M453.122,79.012a128,128,0,0,0-181.087.068l-15.511,15.7L241.142,79.114l-.1-.1a128,128,0,0,0-181.02,0l-6.91,6.91a128,128,0,0,0,0,181.019L235.485,449.314l20.595,21.578.491-.492.533.533L276.4,450.574,460.032,266.94a128.147,128.147,0,0,0,0-181.019ZM437.4,244.313,256.571,425.146,75.738,244.313a96,96,0,0,1,0-135.764l6.911-6.91a96,96,0,0,1,135.713-.051l38.093,38.787,38.274-38.736a96,96,0,0,1,135.765,0l6.91,6.909A96.11,96.11,0,0,1,437.4,244.313Z"></path>
                </svg>
              {% endif %}
            </button>
            <button type="button" title="Add a comment" class="flex items-center justify-center">
              <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" class="w-5 h-5 fill-current">
                <path d="M496,496H480a273.39,273.39,0,0,1-179.025-66.782l-16.827-14.584C274.814,415.542,265.376,416,256,416c-63.527,0-123.385-20.431-168.548-57.529C41.375,320.623,16,270.025,16,216S41.375,111.377,87.452,73.529C132.615,36.431,192.473,16,256,16S379.385,36.431,424.548,73.529C470.625,111.377,496,161.975,496,216a171.161,171.161,0,0,1-21.077,82.151,201.505,201.505,0,0,1-47.065,57.537,285.22,285.22,0,0,0,63.455,97L496,457.373ZM294.456,381.222l27.477,23.814a241.379,241.379,0,0,0,135,57.86,317.5,317.5,0,0,1-62.617-105.583v0l-4.395-12.463,9.209-7.068C440.963,305.678,464,262.429,464,216c0-92.636-93.309-168-208-168S48,123.364,48,216s93.309,168,208,168a259.114,259.114,0,0,0,31.4-1.913Z"></path>
              </svg>
            </button>
            <button type="button" title="Share post" class="flex items-center justify-center">
              <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" class="w-5 h-5 fill-current">
                <path d="M474.444,19.857a20.336,20.336,0,0,0-21.592-2.781L33.737,213.8v38.066l176.037,70.414L322.69,496h38.074l120.3-455.4A20.342,20.342,0,0,0,474.444,19.857ZM337.257,459.693,240.2,310.37,389.553,146.788l-23.631-21.576L215.4,290.069,70.257,232.012,443.7,56.72Z"></path>
              </svg>
            </button>
          </div>
          
          <button type="submit" name="action" value="save" title="Bookmark post" class="flex items-center justify-center">
            {% if user in post.saved.all %}
              <i class="fa-solid fa-bookmark"></i>
            {% else %}
              <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" class="w-5 h-5 fill-current">
                <path d="M424,496H388.75L256.008,381.19,123.467,496H88V16H424ZM120,48V456.667l135.992-117.8L392,456.5V48Z"></path>
              </svg>
            {% endif %}
          </button>
        </div>
        <div class="space-y-4">
          <p class="text-sm">
            <span class="text-base font-semibold"><a href="{% url 'profile' post.author.username %}">{{ post.author.username }}</a></span> {{ post.body }}
          </p>
          <p class="text-xs dark:text-gray-400">{{ post.likes.count }} - likes</p>
          <input type="text" name="comment" placeholder="Add a comment..." class="input input-bordered input-sm max-w-sm">
          <button class="btn btn-sm" name="action" value="comment" type="submit"><span style="color: white;"><i class="fa-solid fa-paper-plane"></i></span></button>
        </div>
    {% if post.comments.all %}
      <div class="flex justify-center"><h1 style="font-size: 30px; color: blueviolet;">Comments</h1><br/><br></div>
    {% else %}
      <div class="flex justify-center"><h1 style="font-size: 30px; color: blueviolet;">No comments yet</h1><br/><br></div>
    {% endif %}

      {% for comment in post.comments.all %}
      <div class="flex space-x-4">
        {% if comment.author.profile_pic %}
          <img alt="" src="{{ comment.author.profile_pic.url }}" class="object-cover w-12 h-12 rounded-full shadow dark:bg-gray-500">
        {% else %}
        <img alt="" src="/media/images/default_picture.jpeg" class="object-cover w-12 h-12 rounded-full shadow dark:bg-gray-500">
        {% endif %}
        <div class="flex flex-col space-y-1">
            <a rel="noopener noreferrer" href="{% url 'profile' comment.author.username %}" class="text-sm font-semibold">{{ comment.author.username }}</a> {{ comment.body }}
            <span class="text-xs dark:text-gray-400">Commented - {{ comment.date_posted }}</span>
          </div>
      </div>
    {% endfor %}
		<br/>

      </div>
    </div>
  </div>
</form>
  <br/><br/><br/>
<script>
  function copyUrl() {

      /* Copy text into clipboard */
      navigator.clipboard.writeText
          ("https://instablogcom.herokuapp.com{% url 'post_details' post.pk %}");
      alert("Copied link to clipboard!");
  }
</script>

{% endblock %}

templates/blog/update_post.html
{% extends 'base.html' %}

{% block title %} Edit Post {% endblock %}


{% block content %}

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="flex justify-center">
        <div class="flex flex-col w-full max-w-md p-12 space-y-4 p-6 rounded-md sm:p-10 dark:bg-gray-900 dark:text-gray-100">
            <h1 style="font-size: 30px; text-align: center;">Edit Post</h1>
            {% if form.errors %}
                <p class="text-sm" style="color: red;">Please correct the errors below.</p>
            {% endif %}

            <fieldset class="w-full space-y-1 dark:text-gray-100">
                <label for="body" class="block text-sm font-medium">Photo: <a href="{{ post.photo.url }}" class="link link-hover link-primary">{{ post.photo }}</a></label>
                <div class="flex">
                    <input type="file"  name="photo" id="id_photo" accept="image/*" class="px-0.1 py-3 border-2 border-dashed rounded-md dark:border-gray-700 dark:text-gray-400 dark:bg-gray-800">
                </div>
            </fieldset>
            <span class="text-sm" style="color: yellow;">{{ form.errors.photo }}</span>
            
        <label for="body" class="block text-sm font-medium">Your message</label>
        <textarea id="id_body" name="body" rows="7" class="block p-2.5 w-full text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-700 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="Your message...">{{ post.body }}</textarea>
        <span class="text-sm" style="color: yellow;">{{ form.errors.body }}</span>
        <button class="btn btn-primary">Save</button>
        
        </div>
    </div>
</form>
<br/><br/><br/>


{% endblock %}